### ISSUE TITLE
I have snowman plugin works well on x32 debugger if i decompiled a little code it works but when i try to decompile larger number of codes this error in pic apears 

### ISSUE THREAD

**Issue by ahmed22pm7** [x64dbg/snowman#13]
![IMG_20230426_170921.jpg](https://user-images.githubusercontent.com/105469178/234935850-10d7f41d-680b-443f-84d0-8228b15e05da.jpg)

**Comment by mrexodia** [comment]
You opened an issue about this yesterday already.
